---
title: "README"
author: "Amy Stringer"
date: "16/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, warning = FALSE, message = FALSE)
```

# The Curriculum {.tabset}

The following has been taken directly from the Australian Curriculum as of May 16th 2021. 

## Topic 1: The Logarithmic Function 

### Logarithmic functions

- define logarithms as indices: $a^x = b$ is equivalent to $x = \log_a b$, i.e $a^{\log_a b} = b$ (ACMMM153)
- establish and use algebraic properties of logarithms (ACMMM152)
- recognise the inverse relationship between logarithms and exponentials: $y = a^x$ is equivalent to $x = \log_a y$ (ACMMM153)
- interpret and use logarithmic scales such as decibels in acoustics, the Richter Scale for earthquake magnitude, octaves in music, pH in chemistry (ACMMM154)
- solve equations involving indices using logarithms (ACMMM155)
- recognise the qualitative features of the graph of $y = \log_a x \, (a>1)$ including asymptotes, and of its translations $y = \log_a x + b$ and $y = \log_a (x + c)$ (ACMMM156)
- solve simple equations involving logarithmic functions algebraically and graphically (ACMMM157)
- identify contexts suitable for modelling by logarithmic functions and use them to solve practical problems. (ACMMM158)
 
### Calculus of logarithmic functions

- define the natural logarithm $\ln x = \log_e x$ (ACMMM159)
- recognise and use the inverse relationship of the functions $y = e^x$ and $y = \ln x$ (ACMMM160)
- establish and use the formula $\frac{d}{dx}(\ln x) = \frac{1}{x}$ (ACMMM161)
- establish and use the formula $\int \frac{1}{x}dx = \ln x + c$ for $x>0$ (ACMMM162)
- use logarithmic functions and their derivatives to solve practical problems. (ACMMM163) 


## Topic 2: Continuous random variables and the normal distribution

### General discrete random variables

- use relative frequencies and histograms obtained from data to estimate probabilities associated with a continuous random variable (ACMMM164)
- understand the concepts of a probability density function, cumulative distribution function, and probabilities associated with a continuous random variable given by integrals; examine simple types of continuous random variables and use them in appropriate contexts (ACMMM165)
- recognise the expected value, variance and standard deviation of a continuous random variable and evaluate them in simple cases (ACMMM166)

### General continuous random variables

- understand the effects of linear changes of scale and origin on the mean and the standard deviation. (ACMMM167)

### Normal distributions

- identify contexts such as naturally occurring variation that are suitable for modelling by normal random variables (ACMMM168)
- recognise features of the graph of the probability density function of the normal distribution with mean $\mu$ and standard deviation $\sigma$ and the use of the standard normal distribution (ACMMM169)
- calculate probabilities and quantiles associated with a given normal distribution using technology, and use these to solve practical problems. (ACMMM170)

## Topic 3: Interval estimates for proportions

### Random sampling

- understand the concept of a random sample (ACMMM171)
- discuss sources of bias in samples, and procedures to ensure randomness (ACMMM172)
- use graphical displays of simulated data to investigate the variability of random samples from various types of distributions, including uniform, normal and Bernoulli. (ACMMM173)

### Sample proportions

- understand the concept of the sample proportion, $\hat{p}$, as a random variable whose value varies between samples, and the formulas for the mean $p$ and standard deviation $\sqrt{(p(1-p)/n)}$ of the sample proportion $\hat{p}$ (ACMMM174)
- examine the approximate normality of the distribution of $\hat{p}$ for large samples  (ACMMM175)
- simulate repeated random sampling, for a variety of values $p$ and a range of sample sizes, to illustrate the distribution of $\hat{p}$ and the approximate standard normality of $\frac{\hat{p}-p}{\sqrt{(\hat{p}(1-\hat{p}))/n}}$ where the closeness of the approximation depends on both $n$ and $p$ (ACMMM176)


### Confidence intervals for proportions

- the concept of an interval estimate for a parameter associated with a random variable (ACMMM177)
- use the approximate confidence interval $(\hat{p} - z\sqrt{(\hat{p}(1-\hat{p}))/n}, \hat{p}+z\sqrt{(\hat{p}(1-\hat{p}))/n})$ (ACMMM178)
- define the approximate margin or error $E = z\sqrt{(\hat{p}(1 - \hat{p}))/n}$ and understand the trade off between margin or error and level of confidence (ACMMM179)
- use simulation to illustrate variations in confidence intervals between samples and to show that most but not all confidence intervals contain $p$ (ACMMM180)


# App Features {.tabset}

## Tab 1 - Welcome 

The welcome tab is designed to give the user an idea of what to expect in the other tabs in the application. 

## Tab 2 - Topic 1 

Topic 1 covers the logarithm function. It contains the formula for the general form of a logarithm, a plot of the logarithm function along with its inverse, and some interactive sliders that the user can use to manipulate the graph. This is designed to familiarise the students with the logarithm function by providing a visual association with the different parameter values. 

Students can stretch, translate, mirror and change the base of the logarithm (between $e, 10$ and $2$).

## Tab 3 - Topic 2

### Welcome 

In the welcome page we give a very brief description of what the activity is about, then a glossary of key terms that will be used throughout this section. 

### Random Variables 

The random variables section provides background information and equations for the key distributions covered in this section of the Cambridge mathematical methods textbook, namely, bernoulli, binomial and normal distributions. 

Students/teachers select the distribution of interest, assign values to the parameters of said distribution and then they can see what the probability density/mass function and cumulative density/mass function look like. They will also see some descriptive text explaining how these can be interpreted, and also the equations for the pdf, expected value and variance. 

### Examples of Other Distributions 

There aren't explicitly any other distributions mentioned in the curriculum or the textbook, but this tab shows the students that there are other distributions outside of the three that they cover. Here we have three other examples of discrete distributions (Geometric, Negative Binomial and Poisson) and three other examples of continuous distributions (Uniform, Exponential and Gamma). 

### Dice Roll Experiment 

The goal of the dice roll experiment is to illustrate the convergence of an experimental expected value to a theoretical expected value. The activity takes a standard dice, gives the user the option to roll once or roll 100 times, and after each roll or set of rolls a cumulative mean is calculated. This mean is then plotted against the number of rolls, and compared to a red line representing the theoretical mean of 3.5. The idea is that as we add more and more rolls, the mean, or expected value, gets closer and closer to the red line.  

## Tab 4 - Topic 3

### Welcome 

Like the other welcome pages, this gives an intro to the activity. The difference here is that it also introduces the virtual reef diver data, giving a brief background on the image annotation process. Just like for the previous topic we have a glossary of key terms to be used throughout the activity. 

### Random Sampling 

In this activity users are expected to use random sampling as a method for approximating the value of $\pi$. This is done by considering $\pi$ as a ratio between the area of a circle and the area of a square. Dropping a number of points onto a square which contains a circle of the same radius allows up to use the number of points inside the square as an estimator of the area (and likewise for the circle). What the user should find is that as we add more and more points to the square and circle, which are chosen randomly, the approximation for the value of $\pi$ gets better and better. This logic can then be extrapolated to conclude that if we have an infinite number of points, we would be able to ascertain the exact value for $\pi$. This activity can be used as a way to highlight the difference between a sample proportion and a population proportion, and the fact that as we approach a sample size close to our population, our estimate becomes better. 

### Sample Proportions 

This activity is fairly limited. The aim is to investigate the long term behaviour of random sampling, and this is the first activity that makes use of the virtual reef diver data. Users will select a classification to investigate out of hard coral, soft coral or algae. Next, they will select the number of images they wish to sample (out of the total 100) using the slider. Once they select a button to sample 10 or 100 times, the program does the following (using "sample 10 times" as an example): 

- selects 10 samples of n images, where n is given by the slider value, at random 
- the proportion of points with the selected classification is computed for each sample 
- a histogram of the proportions for all samples is plotted 

If a button, or combination of buttons, is selected more than once, these new samples are added to the dataset which already exists. This allows the user to inspect the changes in the distribution of proportions as more and more samples are added. 

### Confidence Intervals for Proportions 

In this tab we present an interactive visualisation of the 95% confidence intervals for a proportion. Here we also use the virtual reef diver data. Much like in the previous tab, the user will select a classification and the number of images they would like to sample from the population of 100 images. The user then tells the program to sample once or ten times. Once a button is pressed, the program will pull out the required number of samples, compute the proportion of the chosen classification for each sample and then also compute the 95% confidence interval for that proportion (using the formula given in the Cambridge textbook). 

The proportion and its corresponding confidence intervals are then plotting for each sample. Also shown on the plot is a vertical line indicating the true population proportion for the entire 100 images. The proportions and intervals are then coloured according to whether the interval contains the true population mean. 

Like in the previous tab, the buttons here act as an accumulation of samples, therefore, pressing them multiple times adds more samples to the existing dataset.   

# The Code {.tabset}

The code for this application is contained within the `app.R` file and though it is heavily commented, there are some general details here on how it is structured. 

The code is broken up into three main sections, which is typical for a shiny application: 

- Helper functions 
- User Interface 
- Server 

Each of the User Interface and Server sections are then further split by topic to keep things in order. Below is a list of the Inputs and Outputs that relate to each of the topics discussed in the sections above. 

## Topic 1 - Logarithms 

### Inputs 

- `T1Base` (radio buttons) - Select a base for the logarithm plots from 10, 2, or exp()
- `T1pm` (radio buttons) - Choose whether it will be a positive of negative logarithm 
- `T1h` (slider) - Choose the horizontal translation of the graph 
- `T1v` (slider) - Choose the vertical translation of the graph 
- `T1k` (slider) - Choose how much horizontal stretch to add to the graph 
- `T1a` (slider) - Choose how much vertical stretch to add 

### Outputs 

- `T1LogPlot` (plot output) - This takes all the above inputs, adds them into the general form of the logarithm functions, and plots this using ggplot. 

## Topic 2  - Continuous Random Variables and the Normal Distribution 

### Tab 1 - Random Variables 
#### Inputs 

- `T2Dist` (select input) - Select a distribution between binomial, bernoulli and normal

#### Outputs 

- `T2Options` (ui output) - This communicates with the `T2Dist` input, and provides added inputs depending on the selection 
- `T2header` (ui output) - This also communicates with the `T2Dist` input and updates the header in the main panel to suit the chsen distribution 
- `T2DistInf` (text output) - Provides information on the chosen distribution 
- `T2DistFormula` (ui output) - Provides the relevant formulae for the chosen distribution 
- `T2DistPDF` (plotly output) - interactive plot of the probability mass/density plot for the chosen distribution 
- `T2DistCDF` (plotly output) - interactive plot of the cumulative mass/density plot for the chosen distribution 

### Tab 2 - Examples of Other Distributions 

#### Inputs 

There are no inputs for this tab as it is designed only to give an indication of what other distributions might look like. The parameters for these distributions are beyond the scope for high school mathematics. 

#### Outputs 

- `T2Geometric` (plotly output) - interactive plot of the geometric distribution 
- `T2NegBin` (plotly output) - interactive plot of the negative binomial distribution 
- `T2Poisson` (plotly output) - interactive plot of the poisson distribution 
- `T2Uniform` (plotly output) - interactive plot of the uniform distribution 
- `T2Exponential` (plotly output) - interactive plot of the exponential distribution 
- `T2Gamma` (plotly output) - interactive plot of the gamma distribution 


### Tab 3 - Dice Roll Experiment 
#### Inputs 

- `RollOnce` (action button) - instructs the program to add one roll of a dice to the plot 
- `RollMany` (action button) - instructs the program to roll 100 times and add the results of this to the plot 

#### Outputs 

- `ExpValPlot` (plot output) - plots the expected value after each new roll of a dice and compares this directly to the theoretical expected value. This output works in a reactiveValues framework. 


## Topic 3 - Interval Estimates for Proportions 

### Tab 1 - Random Sampling 

#### Inputs 

- `T3Drop100` (action button) - Drops 100 points at random onto the plot of a square and circle of equal radius. 
- `T3Drop1000` (action button) - Drops 1000 points at random onto the plot of a square and circle of equal radius. 

#### Outputs 

- `T3ValPi` (ui output) - This essentially provides the additional text that shows the computed value of pi in the main panel. This may be done in an easier way. 
- `T3PiEst` (plotly output) - This is the main visualisation in this tab. It shows the square of side length 1, the circle or radius 0.5, and the points which the user drops at random via the action buttons. Points are coloured by which shape they are contained in. The points used to plot here are contained within a reactive dataframe which is updates each time the user uses one of the action buttons. 

### Tab 2 - Sample Proportions 

#### Inputs 

- `T3Classif2` (radio buttons) - selects a classification out of hard coral, soft coral or algae
- `T3nimg2` (slider input) - select the number of images to sample each time 
- `T3Add10` (action button) - tells the program to choose ten samples of `T3nimg2` images 
- `T3Add100` (action button) - tells the program to choose 100 samples of `T3bnimg2` images 

#### Outputs 

- `T3SampleHist` (plot output) - this is a plot of the sample proportions for each sample of the chosen classification. 

### Tab 3 - Confidence Intervals for Proportions 

#### Inputs 

- `T3classif` (radio buttons) - choose a classification to investigate 
- `T3nimg` (slider input) - choose the number of images to sample from the population 
- `T3samp1` (action button) - sample only once 
- `T3sampmany` (action button) - sample 10 times 

#### Outputs 

- `T3ConfIntPlot` (plot output) - This plot shows the proportion of the chosen classification for each sample taken, and its associated confidence interval computed according to the formula given in the main panel. The true population proportion for this classification is included for comparison, and intervals are coloured according to whether they contain this value. 

